version: 2.1 

commands:
  config-environment:
    steps:
      - run: 
          name: Config environment..
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  test-pytest:
    steps:
      - run:
          name: Run test pytest...
          command: |
            . venv/bin/activate
            pytest -v 

executors:
  python37:
    docker:
      - image: circleci/python:3.7

jobs:
  test-code:
    branches:
      only:
        - circleCI
    executor: python37
    steps:
      - test-pytest

workflows:
  flow-pytest:
    jobs:
      - test-code:
          pre-steps:
            - checkout
            - config-environment